logging:
  level:
    org.springframework: INFO
    com.ninjaone.dundie_awards: DEBUG

springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  jpa:
    show-sql: true
  #  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#  jpa:
#    show-sql: true
#    properties:
#      ## Hibernate Properties
#      # The SQL dialect makes Hibernate generate better SQL for the chosen database
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    # Hibernate ddl auto (create, create-drop, validate, update)
#    hibernate:
#      ddl-auto: update
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/static/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

management:
  endpoints:
    web:
      exposure:
        # In a real app, secure non-trivial endpoints
        include: '*'